### ISSUE TITLE
Not support idea 2018.3

### ISSUE THREAD

**Issue by netroby** [mplushnikov/lombok-intellij-plugin#556]
Not support idea 2018.3
Today idea 2018.3 released

**Comment by abrandell** [comment]
Had the same problem but I was using an older version of the plugin. Updating it (v0.22.IDEA-EAP) removed the "Incompatible with the current ... " message. Works fine now with 2018.3.

**Comment by PuGuanyu** [comment]
I rebuilt the project, and it works fine for me with 2018.3.
[lombok-plugin-2018_3.zip](https://github.com/mplushnikov/lombok-intellij-plugin/files/2606715/lombok-plugin-2018_3.zip)

**Comment by ppasler** [comment]
I simple re-enabled the plugin (File > Settings > Plugins), even though it's marked as incompatible. It needed two clicks on the checkbox to enable.

**Comment by strongme** [comment]
> I rebuilt the project, and it works fine for me with 2018.3.
> [lombok-plugin-2018_3.zip](https://github.com/mplushnikov/lombok-intellij-plugin/files/2606715/lombok-plugin-2018_3.zip)

works fine

**Comment by kv1980** [comment]
IntelliJ doesn't find the new Lombok Plugin (File > Settings > Plugins > Browse Repositories) yet.

**Comment by GaCampioto** [comment]
> I rebuilt the project, and it works fine for me with 2018.3.
> [lombok-plugin-2018_3.zip](https://github.com/mplushnikov/lombok-intellij-plugin/files/2606715/lombok-plugin-2018_3.zip)

I've installed the package as above and worked fine 👍

**Comment by Vrakfall** [comment]
I wouldn't trust such user builds. Who knows is there's no dangerous things added to it?

**Comment by PuGuanyu** [comment]
> I wouldn't trust such user builds. Who knows is there's no dangerous things added to it?
You can clone the project and change the version to 2018.3 in gradle.properties, then run `gradlew build`. Then you can get the file in `
build\distributions`.

**Comment by T-XUE** [comment]
> I rebuilt the project, and it works fine for me with 2018.3.
> [lombok-plugin-2018_3.zip](https://github.com/mplushnikov/lombok-intellij-plugin/files/2606715/lombok-plugin-2018_3.zip)

good

**Comment by YinAqu** [comment]
> I rebuilt the project, and it works fine for me with 2018.3.
> [lombok-plugin-2018_3.zip](https://github.com/mplushnikov/lombok-intellij-plugin/files/2606715/lombok-plugin-2018_3.zip)

nice work.

**Comment by dusanmilicevic** [comment]
Reinstalling the plugin and just disable and enable the annotation processing did the job for me.

**Comment by PuGuanyu** [comment]
> > > I wouldn't trust such user builds. Who knows is there's no dangerous things added to it?
> > 
> > 
> > You can clone the project and change the version to 2018.3 in gradle.properties, then run `gradlew build`. Then you can get the file in ` build\distributions`.
> 
> I prefer that approach. :) Also, then it's probably just an easy PR. Do all tests pass?

I didn't modify any code, the only thing I did was changing version rebuilding, and then it works fine with the lastest IDEA.

**Comment by wxch1028** [comment]
> I rebuilt the project, and it works fine for me with 2018.3.
> [lombok-plugin-2018_3.zip](https://github.com/mplushnikov/lombok-intellij-plugin/files/2606715/lombok-plugin-2018_3.zip)

it works fine

**Comment by ginccc** [comment]
just reinstall (uninstall, restart, install, restart) the plugin and it works again.

**Comment by qdlake** [comment]
@PuGuanyu idea 2018.3 + gradle 5.0, lombok-plugin-2018_3.zip still not working

**Comment by c527380322** [comment]
> I rebuilt the project, and it works fine for me with 2018.3.
> [lombok-plugin-2018_3.zip](https://github.com/mplushnikov/lombok-intellij-plugin/files/2606715/lombok-plugin-2018_3.zip)

(uninstall, restart, install, restart) the plugin and it still not working.

**Comment by zgranik** [comment]
Not working for me also, after uninstall, restart, install, restart

**Comment by wildloop** [comment]
> (uninstall, restart, install, restart) the plugin and it still not working.

install downloaded [lombok-plugin-2018_3.zip](https://github.com/mplushnikov/lombok-intellij-plugin/files/2606715/lombok-plugin-2018_3.zip) from disk, restart IntelliJ 2018.3 - works for me.

**Comment by c527380322** [comment]
It's working well now. And I just installed from disk and not restart from plugin, It's just enIt has been reinstalled again and is ready for use. The reason is probably that I restarted in the plugin bar. I just did not select the restart item of the plugin bar after installation, but chose “apply” and “OK”, then the main page prompts to restart.


> Not working for me also, after uninstall, restart, install, restart



> @PuGuanyu idea 2018.3 + gradle 5.0, lombok-plugin-2018_3.zip still not working

**Comment by c527380322** [comment]
It has been reinstalled again and is ready for use. The reason is probably that I restarted in the plugin bar. I just did not select the restart item of the plugin bar after installation, but chose “apply” and “OK”, then the main page prompts to restart.



> Not working for me also, after uninstall, restart, install, restart



> @PuGuanyu idea 2018.3 + gradle 5.0, lombok-plugin-2018_3.zip still not working

**Comment by keke2014** [comment]
> I rebuilt the project, and it works fine for me with 2018.3.
> [lombok-plugin-2018_3.zip](https://github.com/mplushnikov/lombok-intellij-plugin/files/2606715/lombok-plugin-2018_3.zip)

It works for me too.

**Comment by lizhaosheng** [comment]
> > I rebuilt the project, and it works fine for me with 2018.3.
> > [lombok-plugin-2018_3.zip](https://github.com/mplushnikov/lombok-intellij-plugin/files/2606715/lombok-plugin-2018_3.zip)
> 
> not works for me.
> Version: 2018.3.1
> Build: 183.4588.61
> Released: December 5, 2018
> 
> 018-12-06 10:37:15,335 [87840758] WARN - nal.AbstractExternalSystemTask - Could not find method c() for arguments [org.projectlombok:lombok:1.18.4] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.
> com.intellij.openapi.externalSystem.model.LocationAwareExternalSystemException: Could not find method c() for arguments [org.projectlombok:lombok:1.18.4] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.
> at com.android.tools.idea.gradle.project.sync.idea.ProjectImportErrorHandler.getUserFriendlyError(ProjectImportErrorHandler.java:68)
> at com.android.tools.idea.gradle.project.sync.idea.AndroidGradleProjectResolver.getUserFriendlyError(AndroidGradleProjectResolver.java:427)
> at org.jetbrains.plugins.gradle.service.project.AbstractProjectResolverExtension.getUserFriendlyError(AbstractProjectResolverExtension.java:150)
> at org.jetbrains.plugins.gradle.service.project.AbstractProjectResolverExtension.getUserFriendlyError(AbstractProjectResolverExtension.java:150)
> at org.jetbrains.plugins.gradle.service.project.AbstractProjectResolverExtension.getUserFriendlyError(AbstractProjectResolverExtension.java:150)
> at org.jetbrains.plugins.gradle.service.project.JavaGradleProjectResolver.getUserFriendlyError(JavaGradleProjectResolver.java:94)
> at org.jetbrains.plugins.gradle.service.project.AbstractProjectResolverExtension.getUserFriendlyError(AbstractProjectResolverExtension.java:150)
> at org.jetbrains.plugins.gradle.service.project.AbstractProjectResolverExtension.getUserFriendlyError(AbstractProjectResolverExtension.java:150)
> at org.jetbrains.plugins.gradle.service.project.GradleProjectResolver$ProjectConnectionDataNodeFunction.fun(GradleProjectResolver.java:883)
> at org.jetbrains.plugins.gradle.service.project.GradleProjectResolver$ProjectConnectionDataNodeFunction.fun(GradleProjectResolver.java:862)
> at org.jetbrains.plugins.gradle.service.execution.GradleExecutionHelper.execute(GradleExecutionHelper.java:217)
> at org.jetbrains.plugins.gradle.service.project.GradleProjectResolver.resolveProjectInfo(GradleProjectResolver.java:141)
> at org.jetbrains.plugins.gradle.service.project.GradleProjectResolver.resolveProjectInfo(GradleProjectResolver.java:76)
> at com.intellij.openapi.externalSystem.service.remote.RemoteExternalSystemProjectResolverImpl.a(RemoteExternalSystemProjectResolverImpl.java:37)
> at com.intellij.openapi.externalSystem.service.remote.AbstractRemoteExternalSystemService.execute(AbstractRemoteExternalSystemService.java:58)
> at com.intellij.openapi.externalSystem.service.remote.RemoteExternalSystemProjectResolverImpl.resolveProjectInfo(RemoteExternalSystemProjectResolverImpl.java:37)
> at com.intellij.openapi.externalSystem.service.remote.wrapper.ExternalSystemProjectResolverWrapper.resolveProjectInfo(ExternalSystemProjectResolverWrapper.java:45)
> at com.intellij.openapi.externalSystem.service.internal.ExternalSystemResolveProjectTask.doExecute(ExternalSystemResolveProjectTask.java:100)
> at com.intellij.openapi.externalSystem.service.internal.AbstractExternalSystemTask.execute(AbstractExternalSystemTask.java:166)
> at com.intellij.openapi.externalSystem.service.internal.AbstractExternalSystemTask.execute(AbstractExternalSystemTask.java:152)
> at com.intellij.openapi.externalSystem.util.ExternalSystemUtil$3.execute(ExternalSystemUtil.java:554)
> at com.intellij.openapi.externalSystem.util.ExternalSystemUtil$5.run(ExternalSystemUtil.java:659)
> at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:727)
> at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:164)
> at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:582)
> at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:532)
> at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:87)
> at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:151)
> at com.intellij.openapi.progress.impl.CoreProgressManager$4.run(CoreProgressManager.java:403)
> at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:314)
> at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
> at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
> at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
> at java.lang.Thread.run(Thread.java:745)
> Caused by: org.gradle.internal.metaobject.AbstractDynamicObject$CustomMessageMissingMethodException: Could not find method c() for arguments [org.projectlombok:lombok:1.18.4] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.
> at org.gradle.internal.metaobject.AbstractDynamicObject.methodMissingException(AbstractDynamicObject.java:179)
> at org.gradle.internal.metaobject.ConfigureDelegate.invokeMethod(ConfigureDelegate.java:87)
> at build_kjlmh0z5n1mageorho88bu2a$_run_closure3.doCall(/Users/lizhaosheng/dev/workspace-idea/common-grpc/build.gradle:38)
> at org.gradle.util.ClosureBackedAction.execute(ClosureBackedAction.java:70)
> at org.gradle.util.ConfigureUtil.configureTarget(ConfigureUtil.java:154)
> at org.gradle.util.ConfigureUtil.configure(ConfigureUtil.java:105)
> at org.gradle.api.internal.project.DefaultProject.dependencies(DefaultProject.java:1182)
> at org.gradle.internal.metaobject.BeanDynamicObject$MetaClassAdapter.invokeMethod(BeanDynamicObject.java:479)
> at org.gradle.internal.metaobject.BeanDynamicObject.tryInvokeMethod(BeanDynamicObject.java:191)
> at org.gradle.internal.metaobject.CompositeDynamicObject.tryInvokeMethod(CompositeDynamicObject.java:98)
> at org.gradle.internal.metaobject.MixInClosurePropertiesAsMethodsDynamicObject.tryInvokeMethod(MixInClosurePropertiesAsMethodsDynamicObject.java:30)
> at org.gradle.groovy.scripts.BasicScript$ScriptDynamicObject.tryInvokeMethod(BasicScript.java:133)
> at org.gradle.internal.metaobject.AbstractDynamicObject.invokeMethod(AbstractDynamicObject.java:160)
> at org.gradle.groovy.scripts.BasicScript.invokeMethod(BasicScript.java:82)
> at build_kjlmh0z5n1mageorho88bu2a.run(/Users/lizhaosheng/dev/workspace-idea/common-grpc/build.gradle:34)
> at org.gradle.groovy.scripts.internal.DefaultScriptRunnerFactory$ScriptRunnerImpl.run(DefaultScriptRunnerFactory.java:90)
> at org.gradle.configuration.DefaultScriptPluginFactory$ScriptPluginImpl$2.run(DefaultScriptPluginFactory.java:206)
> at org.gradle.configuration.ProjectScriptTarget.addConfiguration(ProjectScriptTarget.java:77)
> at org.gradle.configuration.DefaultScriptPluginFactory$ScriptPluginImpl.apply(DefaultScriptPluginFactory.java:211)
> at org.gradle.configuration.BuildOperationScriptPlugin$1$1.run(BuildOperationScriptPlugin.java:69)
> at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:301)
> at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:293)
> at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:175)
> at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:91)
> at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
> at org.gradle.configuration.BuildOperationScriptPlugin$1.execute(BuildOperationScriptPlugin.java:66)
> at org.gradle.configuration.BuildOperationScriptPlugin$1.execute(BuildOperationScriptPlugin.java:63)
> at org.gradle.configuration.internal.DefaultUserCodeApplicationContext.apply(DefaultUserCodeApplicationContext.java:48)
> at org.gradle.configuration.BuildOperationScriptPlugin.apply(BuildOperationScriptPlugin.java:63)
> at org.gradle.configuration.project.BuildScriptProcessor$1.run(BuildScriptProcessor.java:44)
> at org.gradle.internal.Factories$1.create(Factories.java:25)
> at org.gradle.api.internal.project.DefaultProjectStateRegistry$ProjectStateImpl.withMutableState(DefaultProjectStateRegistry.java:200)
> at org.gradle.api.internal.project.DefaultProjectStateRegistry$ProjectStateImpl.withMutableState(DefaultProjectStateRegistry.java:186)
> at org.gradle.configuration.project.BuildScriptProcessor.execute(BuildScriptProcessor.java:41)
> at org.gradle.configuration.project.BuildScriptProcessor.execute(BuildScriptProcessor.java:26)
> at org.gradle.configuration.project.ConfigureActionsProjectEvaluator.evaluate(ConfigureActionsProjectEvaluator.java:34)
> at org.gradle.configuration.project.LifecycleProjectEvaluator$EvaluateProject$1.run(LifecycleProjectEvaluator.java:107)
> at org.gradle.internal.Factories$1.create(Factories.java:25)
> at org.gradle.internal.work.DefaultWorkerLeaseService.withLocks(DefaultWorkerLeaseService.java:183)
> at org.gradle.internal.work.StopShieldingWorkerLeaseService.withLocks(StopShieldingWorkerLeaseService.java:40)
> at org.gradle.api.internal.project.DefaultProjectStateRegistry$ProjectStateImpl.withProjectLock(DefaultProjectStateRegistry.java:226)
> at org.gradle.api.internal.project.DefaultProjectStateRegistry$ProjectStateImpl.withMutableState(DefaultProjectStateRegistry.java:220)
> at org.gradle.api.internal.project.DefaultProjectStateRegistry$ProjectStateImpl.withMutableState(DefaultProjectStateRegistry.java:186)
> at org.gradle.configuration.project.LifecycleProjectEvaluator$EvaluateProject.run(LifecycleProjectEvaluator.java:96)
> at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:301)
> at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:293)
> at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:175)
> at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:91)
> at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
> at org.gradle.configuration.project.LifecycleProjectEvaluator.evaluate(LifecycleProjectEvaluator.java:68)
> at org.gradle.api.internal.project.DefaultProject.evaluate(DefaultProject.java:687)
> at org.gradle.api.internal.project.DefaultProject.evaluate(DefaultProject.java:140)
> at org.gradle.execution.TaskPathProjectEvaluator.configure(TaskPathProjectEvaluator.java:35)
> at org.gradle.execution.TaskPathProjectEvaluator.configureHierarchy(TaskPathProjectEvaluator.java:60)
> at org.gradle.configuration.DefaultBuildConfigurer.configure(DefaultBuildConfigurer.java:41)
> at org.gradle.initialization.DefaultGradleLauncher$ConfigureBuild.run(DefaultGradleLauncher.java:286)
> at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:301)
> at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:293)
> at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:175)
> at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:91)
> at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
> at org.gradle.initialization.DefaultGradleLauncher.configureBuild(DefaultGradleLauncher.java:194)
> at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:150)
> at org.gradle.initialization.DefaultGradleLauncher.getConfiguredBuild(DefaultGradleLauncher.java:128)
> at org.gradle.internal.invocation.GradleBuildController$2.execute(GradleBuildController.java:88)
> at org.gradle.internal.invocation.GradleBuildController$2.execute(GradleBuildController.java:85)
> at org.gradle.internal.invocation.GradleBuildController$3.create(GradleBuildController.java:103)
> at org.gradle.internal.invocation.GradleBuildController$3.create(GradleBuildController.java:96)
> at org.gradle.internal.work.DefaultWorkerLeaseService.withLocks(DefaultWorkerLeaseService.java:183)
> at org.gradle.internal.work.StopShieldingWorkerLeaseService.withLocks(StopShieldingWorkerLeaseService.java:40)
> at org.gradle.internal.invocation.GradleBuildController.doBuild(GradleBuildController.java:96)
> at org.gradle.internal.invocation.GradleBuildController.configure(GradleBuildController.java:85)
> at org.gradle.tooling.internal.provider.runner.ClientProvidedBuildActionRunner.run(ClientProvidedBuildActionRunner.java:70)
> at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
> at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
> at org.gradle.tooling.internal.provider.ValidatingBuildActionRunner.run(ValidatingBuildActionRunner.java:32)
> at org.gradle.launcher.exec.RunAsBuildOperationBuildActionRunner$3.run(RunAsBuildOperationBuildActionRunner.java:49)
> at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:301)
> at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:293)
> at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:175)
> at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:91)
> at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
> at org.gradle.launcher.exec.RunAsBuildOperationBuildActionRunner.run(RunAsBuildOperationBuildActionRunner.java:44)
> at org.gradle.tooling.internal.provider.SubscribableBuildActionRunner.run(SubscribableBuildActionRunner.java:51)
> at org.gradle.launcher.exec.InProcessBuildActionExecuter$1.transform(InProcessBuildActionExecuter.java:47)
> at org.gradle.launcher.exec.InProcessBuildActionExecuter$1.transform(InProcessBuildActionExecuter.java:44)
> at org.gradle.composite.internal.DefaultRootBuildState.run(DefaultRootBuildState.java:79)
> at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:44)
> at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:30)
> at org.gradle.launcher.exec.BuildTreeScopeBuildActionExecuter.execute(BuildTreeScopeBuildActionExecuter.java:39)
> at org.gradle.launcher.exec.BuildTreeScopeBuildActionExecuter.execute(BuildTreeScopeBuildActionExecuter.java:25)
> at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:78)
> at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:52)
> at org.gradle.tooling.internal.provider.ServicesSetupBuildActionExecuter.execute(ServicesSetupBuildActionExecuter.java:62)
> at org.gradle.tooling.internal.provider.ServicesSetupBuildActionExecuter.execute(ServicesSetupBuildActionExecuter.java:34)
> at org.gradle.tooling.internal.provider.GradleThreadBuildActionExecuter.execute(GradleThreadBuildActionExecuter.java:36)
> at org.gradle.tooling.internal.provider.GradleThreadBuildActionExecuter.execute(GradleThreadBuildActionExecuter.java:25)
> at org.gradle.tooling.internal.provider.ParallelismConfigurationBuildActionExecuter.execute(ParallelismConfigurationBuildActionExecuter.java:43)
> at org.gradle.tooling.internal.provider.ParallelismConfigurationBuildActionExecuter.execute(ParallelismConfigurationBuildActionExecuter.java:29)
> at org.gradle.tooling.internal.provider.StartParamsValidatingActionExecuter.execute(StartParamsValidatingActionExecuter.java:59)
> at org.gradle.tooling.internal.provider.StartParamsValidatingActionExecuter.execute(StartParamsValidatingActionExecuter.java:31)
> at org.gradle.tooling.internal.provider.SessionFailureReportingActionExecuter.execute(SessionFailureReportingActionExecuter.java:59)
> at org.gradle.tooling.internal.provider.SessionFailureReportingActionExecuter.execute(SessionFailureReportingActionExecuter.java:44)
> at org.gradle.tooling.internal.provider.SetupLoggingActionExecuter.execute(SetupLoggingActionExecuter.java:46)
> at org.gradle.tooling.internal.provider.SetupLoggingActionExecuter.execute(SetupLoggingActionExecuter.java:30)
> at org.gradle.launcher.daemon.server.exec.ExecuteBuild.doBuild(ExecuteBuild.java:67)
> at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
> at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:122)
> at org.gradle.launcher.daemon.server.exec.WatchForDisconnection.execute(WatchForDisconnection.java:37)
> at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:122)
> at org.gradle.launcher.daemon.server.exec.ResetDeprecationLogger.execute(ResetDeprecationLogger.java:26)
> at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:122)
> at org.gradle.launcher.daemon.server.exec.RequestStopIfSingleUsedDaemon.execute(RequestStopIfSingleUsedDaemon.java:34)
> at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:122)
> at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:74)
> at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:72)
> at org.gradle.util.Swapper.swap(Swapper.java:38)
> at org.gradle.launcher.daemon.server.exec.ForwardClientInput.execute(ForwardClientInput.java:72)
> at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:122)
> at org.gradle.launcher.daemon.server.exec.LogAndCheckHealth.execute(LogAndCheckHealth.java:55)
> at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:122)
> at org.gradle.launcher.daemon.server.exec.LogToClient.doBuild(LogToClient.java:62)
> at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
> at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:122)
> at org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment.doBuild(EstablishBuildEnvironment.java:81)
> at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
> at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:122)
> at org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy$1.run(StartBuildOrRespondWithBusy.java:50)
> at org.gradle.launcher.daemon.server.DaemonStateCoordinator$1.run(DaemonStateCoordinator.java:295)
> at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
> at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
> at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)

OK, I know what is going on. 
Gradle 5.0 doesn't work well with lombok. While I turned to gradle 4.3.1, it works.

**Comment by thetric** [comment]
@lizhaosheng looks like a typo in your `build.gradle`:

```
Could not find method c() for arguments [org.projectlombok:lombok:1.18.4]
                      ^^^
```

It should be

```gradle
annotationProcessor 'org.projectlombok:lombok:1.18.4'
compileOnly 'org.projectlombok:lombok:1.18.4'
```

**Comment by thetric** [comment]
I guess this issue can be closed?

**Comment by frjtrifork** [comment]
> The version of the currently installed Lombok plugin is 0.22.2018.2.
> If you say this warning can safely be ignored (why?), then fine. Since I need to get work done on this machine, I don't feel like being adventurous...

I have v0.22.IDEA-EAP and tried Update and Restart and as the warning says it does not work with 2018.3. 

To make it work with 2018.3 you have to uninstall the Lombok 0.22 plugin, restart Idea, download this updated plugin and in the Plugins menu click "install from disk" and select the downloaded zip file:
https://github.com/mplushnikov/lombok-intellij-plugin/files/2606715/lombok-plugin-2018_3.zip

Restart Idea once again and you are good to go

**Comment by dtrunk90** [comment]
Today I've updated my IntelliJ IDE by ignoring the incompatibility message. After a restart I got a notification about the availability of the Lombok plugin. I updated the plugin and everything worked well.

**Comment by mplushnikov** [comment]
Just released new version of plugin, build for IDEA-2018.3
Any warning during upgrade from 2018.2 about plugin incompatibility can be ignored. After IDEA upgrade, you will be find compatible version in Jetbrains plugin repository as usual.

**Comment by zgranik** [comment]
![image](https://user-images.githubusercontent.com/29770569/50155939-b7665900-02cd-11e9-8aa1-25815d5868ce.png)
![image](https://user-images.githubusercontent.com/29770569/50155954-c0572a80-02cd-11e9-93f6-960c5bc9c6b1.png)
I am still having issues...even after uninstal restart intall restart..?

**Comment by ieugen** [comment]
So many times lombok gradle and idea break.. It's starting to look like a bad romance...

**Comment by ieugen** [comment]
The solution might be to use the idea plugin https://github.com/gradle/gradle/issues/6227 . Did not try it.

**Comment by zhaoxi1988** [comment]
Had the same problem
